name: 'aws-secrets-manager-actions'
description: 'GitHub Actions for AWS Secrets Manager'
inputs:
  SECRET_NAME:
    description: 'Set secret name that you want to get.'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'Set Aws Access Key ID'
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: 'Set Aws Secret access Key'
    required: false
  AWS_SESSION_TOKEN:
    description: 'Set Aws Session token Key'
    required: false
  AWS_DEFAULT_REGION:
    description: 'Set Aws default region'
    required: false
  OUTPUT_PATH:
    description: 'Set output file where variables are write'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'orange'
